# Dockerfile
FROM python:3.9.10-alpine3.14
WORKDIR /home/tigerhall/webApp
RUN pip install --upgrade pip
RUN pip install flask requests pkce
COPY ./webApp/. /home/tigerhall/webApp
ENV FLASK_APP=app
CMD ["python","app.py"]