version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysqldb:/var/lib/mysql

  mysqldb-migrate:
    image: liquibase/liquibase
    volumes:
      - ./migrations:/liquibase/changelog
      - ./migrations/resources:/liquibase/changelog/resources
      - ./migrations/lib/mysql-connector-java-8.0.30.jar:/liquibase/lib/mysql-connector-java-8.0.30.jar
    environment:
      - MIGRATION_CONTEXT=$MIGRATION_CONTEXT
    command: [
      "--url=jdbc:mysql://mysqldb:$DB_PORT/$DB_NAME",
      "--username=$DB_USER",
      "--password=$DB_PASSWORD",
      "--driver=com.mysql.cj.jdbc.Driver",
      "--classpath=changelog/lib/mysql-connector-java-8.0.30.jar",
      "--contexts=$MIGRATION_CONTEXT",
      "--changelog-file=changelog/changelog.xml",
      "update"
    ]
    depends_on:
      - mysqldb

  tiger-tracker-api:
    image: tiger-tracker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    depends_on:
      - mysqldb-migrate
    working_dir: /home/tigerhall
    volumes:
      - ./configuration:/home/tigerhall/configuration
    command: [ "./tiger-tracker-api" ]

volumes:
  mysqldb:
    driver: local