version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=tigerhall
      - MYSQL_USER=tiger
      - MYSQL_PASSWORD=kitten
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysql

  mysqldb-migrate:
    image: liquibase/liquibase
    volumes:
      - ./migrations:/liquibase/changelog
      - ./migrations/lib/mysql-connector-java-8.0.30.jar:/liquibase/lib/mysql-connector-java-8.0.30.jar
    command: [
      "--url=jdbc:mysql://mysqldb:3306/tigerhall",
      "--username=tiger",
      "--password=kitten",
      "--driver=com.mysql.cj.jdbc.Driver",
      "--classpath=changelog/lib/mysql-connector-java-8.0.30.jar",
      "--contexts=local",
      "--changelog-file=changelog/changelog.xml",
      "update"
    ]
    depends_on:
      - mysqldb

  tiger-tracker-api:
    image: tiger-tracker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USER=tiger
      - DB_PASSWORD=kitten
      - DB_NAME=tigerhall
    depends_on:
      - mysqldb-migrate
    working_dir: /home/tigerhall
    volumes:
      - ./configuration:/home/tigerhall/configuration
    command: [ "./tiger-tracker-api" ]

volumes:
  mysqldb:
    driver: local