definitions:
  apiError.APIError:
    properties:
      errorCode:
        $ref: '#/definitions/apiError.ErrorCode'
      errorMessage:
        type: string
    type: object
  apiError.ErrorCode:
    enum:
    - ERR_BAD_REQUEST
    type: string
    x-enum-varnames:
    - BadRequestErrorCode
  models.ListTigersResponse:
    properties:
      tigers:
        items:
          $ref: '#/definitions/models.TigerDetailWithSightings'
        type: array
    type: object
  models.Location:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  models.SignupResponse:
    properties:
      status:
        type: string
    type: object
  models.TigerDetailWithSightings:
    properties:
      dob:
        type: string
      lastPosition:
        $ref: '#/definitions/models.Location'
      lastSeen:
        type: string
      tigerName:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health:
    get:
      description: Confirms if the API Service is up and running
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Checks API Service health
      tags:
      - Health
  /v1/login/password:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Accepts the login consent when credentials are correct and redirects
        to the consent page.
      parameters:
      - description: login challenge
        in: formData
        name: login_challenge
        required: true
        type: string
      - description: login user name
        in: formData
        name: user_name
        required: true
        type: string
      - description: login password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/apiError.APIError'
      summary: Identity provider api to verify login.
      tags:
      - Login
  /v1/signup:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Creates a new user.
      parameters:
      - description: user name
        in: formData
        name: user_name
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SignupResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiError.APIError'
      summary: Creates a new user.
      tags:
      - Signup
  /v1/tigers:
    get:
      description: It is a paginated endpoint. The tigers are sorted by the last time
        they were seen.
      parameters:
      - description: page number
        in: query
        name: pageNo
        required: true
        type: integer
      - description: page size
        in: query
        name: pageSize
        required: true
        type: integer
      - description: starts with Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListTigersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiError.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiError.APIError'
      summary: Returns a list of all the tigers with their details.
      tags:
      - Tigers
swagger: "2.0"
